<template>
<div class="about animated fadeIn">
    <b-row>
      <b-col md="12"  class="top-padding">
        <br class="py-2 d-sm-block d-md-none">
        <div class="bordaForm">
          <h2 class="text-center aboutHeader pb-1">ABOUT</h2>
          <div class="paddingBottomDiv d-none d-lg-block">
            <p><v-icon name="brands/twitch" flip="horizontal" scale="2" class="pb-2"/>Twitch Chat Logs is a search engine for the log files generated by <a href="https://chatty.github.io/">chatty</a> from twitch channels.</p>
            <p><v-icon name="brands/twitch" flip="horizontal" scale="2" class="pb-2"/>You can search by username, message, date or timestamp.</p>
            <p><v-icon name="brands/twitch" flip="horizontal" scale="2" class="pb-2"/> Database updates are made daily.</p>
          </div>
          <div class="paddingBottomDivsm d-sm-block d-md-none">
            <p class="text-left"><v-icon name="brands/twitch" flip="horizontal" scale="2" class="pb-2"/>Twitch Chat Logs is a search engine for the log files generated by <a href="https://chatty.github.io/">chatty</a> from twitch channels.</p>
            <p class="text-left"><v-icon name="brands/twitch" flip="horizontal" scale="2" class="pb-2"/>You can search by username, message, date or timestamp.</p>
            <p><v-icon name="brands/twitch" flip="horizontal" scale="2" class="pb-2"/>Database updates are made daily.</p>
          </div>
        </div>
         <div class="bordaForm d-none d-lg-block my-3">
          <h2 class="text-center aboutHeader">CONTACT</h2>
          <b-row>
            <b-col md="6">
              <h4 class="pl-4"><v-icon name="envelope" scale="2"/> fabricio22101985@gmail.com</h4>
            </b-col>
            <b-col md="6">
              <div class="d-flex justify-content-end pr-4">
                <a class="linkCard px-2 linkContact" href="https://t.me/fabricio2210"><h2><font-awesome-icon :icon="['fab', 'telegram']" /></h2></a>
                <a class="linkCard px-2 linkContact" href="https://api.whatsapp.com/send?phone=5521974719720&text=ol%C3%A1"><h2><font-awesome-icon :icon="['fab', 'whatsapp']" /></h2></a>
                <a class="linkCard px-2 linkContact" href="https://github.com/Fabricio2210"><h2><font-awesome-icon :icon="['fab', 'github']" /></h2></a>
              </div>
            </b-col>
          </b-row>
        </div>
         <div class="bordaForm d-sm-block d-md-none my-3">
          <h2 class="text-center aboutHeader">CONTACT</h2>
          <b-row>
            <b-col md="6">
              <h5 class="pl-2"><v-icon name="envelope" scale="2"/> fabricio22101985@gmail.com</h5>
            </b-col>
            <b-col md="6">
              <div class="d-flex justify-content-center pr-4">
                <a class="linkCard px-2 linkContact" href="https://t.me/fabricio2210"><h2><font-awesome-icon :icon="['fab', 'telegram']" /></h2></a>
                <a class="linkCard px-2 linkContact" href="https://api.whatsapp.com/send?phone=5521974719720&text=ol%C3%A1"><h2><font-awesome-icon :icon="['fab', 'whatsapp']" /></h2></a>
                <a class="linkCard px-2 linkContact" href="https://github.com/Fabricio2210"><h2><font-awesome-icon :icon="['fab', 'github']" /></h2></a>
              </div>
            </b-col>
          </b-row>
        </div>
      </b-col>
    </b-row>
  </div>
</template>

<style scoped>
  .linkContact{
    color: black !important
  }
  .top-padding{
    padding-top: 70px !important;
  }
</style>